SELECT * FROM (SELECT 
LPAD (1, 2, 0) || '|' ||
'VENDAS' || '|' ||
LPAD (50, 3, 0) || '|' ||
:SEQUENCIA || '|' ||
TO_CHAR(SYSDATE-1,'YYYYMMDDhhmi')|| '|' ||
TO_CHAR(SYSDATE-1,'YYYYMMDD')|| '|' ||
TO_CHAR(SYSDATE-1,'YYYYMMDD') || '|' ||
'16731862000124' || '|' ||
'07216054000138',1
FROM DUAL
union all
SELECT 
LPAD (2, 2, 0) || '|' ||
LPAD (1, 2, 0) || '|' ||
LPAD(PCMOV.NUMNOTA,20,0) || '|' ||
LPAD (1, 2, 0) || '|' ||
case 
when PCMOV.CODOPER='S' then '01'
when PCMOV.CODOPER='ST' then '01'
when PCMOV.CODOPER='SR' then '01'
when PCMOV.CODOPER='ED' then '02'
 else '02' end || '|' ||
TO_CHAR(PCMOV.DTMOV,'YYYYMMDD')|| '|' ||
LPAD (0, 20, 0) || '|' ||
LPAD(REPLACE(REPLACE(REPLACE(PCCLIENT.CGCENT,'-',''),'.',''),'/',''),20,0)|| '|' ||
'RJ' || '|' ||
'21010410' || '|' ||
PCCLIENT.ESTCOB || '|' ||
LPAD (0, 8, 0) || '|' ||
'CIF' || '|' ||
LPAD (1, 2, 0) ,PCMOV.NUMNOTA
FROM  PCNFSAID,
       PCPRODUT,
       PCMOV,
       PCCLIENT,
       PCUSUARI,
       PCSUPERV,
       PCPLPAG,
       PCFORNEC,
       PCATIVI, 
       PCPRACA,
       PCDEPTO,
       PCSECAO,
       PCPEDC,
       PCGERENTE,
       PCCIDADE,
       PCMARCA,
       PCROTAEXP,
       PCMOVCOMPLE
WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
   AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL 
   AND PCMOV.DTMOV BETWEEN  TO_DATE('01/02/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('28/02/2023', 'DD/MM/YYYY') 
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND PCNFSAID.CODPRACA = PCPRACA.CODPRACA(+)
   AND PCATIVI.CODATIV(+) = PCCLIENT.CODATV1
   AND PCMOV.CODCLI = PCCLIENT.CODCLI
   AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
   AND  PCNFSAID.CODUSUR   = PCUSUARI.CODUSUR 
   AND PCPRACA.ROTA = PCROTAEXP.CODROTA(+)
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
  AND PCMOV.CODOPER <> 'SR' 
  AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR', 'DF')
  AND PCMOV.CODOPER <> 'SO' 
   AND  NVL(PCNFSAID.CODSUPERVISOR,PCSUPERV.CODSUPERVISOR)   = PCSUPERV.CODSUPERVISOR
   AND PCNFSAID.CODPLPAG = PCPLPAG.CODPLPAG
   AND PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND DECODE(PCNFSAID.CODGERENTE,NULL,PCSUPERV.CODGERENTE,PCNFSAID.CODGERENTE) = PCGERENTE.CODGERENTE 
   AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
   AND (PCNFSAID.DTCANCEL IS NULL)
   AND (PCPRODUT.CODFORNEC IN ( 16154,32194 )) 
   AND PCNFSAID.DTSAIDA BETWEEN  TO_DATE('01/02/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('28/02/2023', 'DD/MM/YYYY') 
           AND PCMOV.CODFILIAL IN('1','2','3','4','7','8','9','11','12','13','14','16')
           AND PCNFSAID.CODFILIAL IN('1','2','3','4','7','8','9','11','12','13','14','16')


UNION ALL
SELECT 
LPAD (3, 2, 0) || '|' ||
LPAD(PCMOV.NUMNOTA,20,0) || '|' ||
LPAD (1, 2, 0) || '|' ||
case 
when PCMOV.CODOPER='S' then '01'
when PCMOV.CODOPER='ST' then '01'
when PCMOV.CODOPER='SR' then '01'
when PCMOV.CODOPER='ED' then '02'
 else '02' end || '|' ||
LPAD (PCMOV.CODPROD, 13, ' ') || '|' ||
LPAD (PCMOV.qt, 10, 0) || '|' ||
case when PCMOV.PUNIT < 1 then TO_CHAR(PCMOV.PUNIT,'0.99')
when PCMOV.PUNIT < 1 then TO_CHAR(PCMOV.PUNIT,'0.99')
 else TO_CHAR(PCMOV.PUNIT,'999.99') end || '|' ||
LPAD ('N', 1, 0) || '|' ||
case when PCMOV.QT*PCMOV.PUNIT < 1 then TO_CHAR(PCMOV.QT*PCMOV.PUNIT,'0.99') when PCMOV.QT*PCMOV.PUNIT > 1 and PCMOV.QT*PCMOV.PUNIT < 99999 then TO_CHAR(PCMOV.QT*PCMOV.PUNIT,'99999.99') else TO_CHAR(PCMOV.QT*PCMOV.PUNIT,'999999.99') end || '|' ||
--case when P.QT*P.PUNIT < 1 then TO_CHAR(P.QT*P.PUNIT,'0.99') else TO_CHAR(P.QT*P.PUNIT,'99999.99') end || '|' ||
case when PCMOV.QT*PCMOV.PUNIT < 1 then TO_CHAR(PCMOV.QT*PCMOV.PUNIT,'0.99') when PCMOV.QT*PCMOV.PUNIT > 1 and PCMOV.QT*PCMOV.PUNIT < 99999 then TO_CHAR(PCMOV.QT*PCMOV.PUNIT,'99999.99') else TO_CHAR(PCMOV.QT*PCMOV.PUNIT,'999999.99') end || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0),PCMOV.NUMNOTA 
  FROM PCNFSAID,
       PCPRODUT,
       PCMOV,
       PCCLIENT,
       PCUSUARI,
       PCSUPERV,
       PCPLPAG,
       PCFORNEC,
       PCATIVI, 
       PCPRACA,
       PCDEPTO,
       PCSECAO,
       PCPEDC,
       PCGERENTE,
       PCCIDADE,
       PCMARCA,
       PCROTAEXP,
       PCMOVCOMPLE
WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
   AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL 
   AND PCMOV.DTMOV BETWEEN  TO_DATE('01/02/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('28/02/2023', 'DD/MM/YYYY') 
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND PCNFSAID.CODPRACA = PCPRACA.CODPRACA(+)
   AND PCATIVI.CODATIV(+) = PCCLIENT.CODATV1
   AND PCMOV.CODCLI = PCCLIENT.CODCLI
   AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
   AND  PCNFSAID.CODUSUR   = PCUSUARI.CODUSUR 
   AND PCPRACA.ROTA = PCROTAEXP.CODROTA(+)
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
  AND PCMOV.CODOPER <> 'SR' 
  AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR', 'DF')
  AND PCMOV.CODOPER <> 'SO' 
   AND  NVL(PCNFSAID.CODSUPERVISOR,PCSUPERV.CODSUPERVISOR)   = PCSUPERV.CODSUPERVISOR
   AND PCNFSAID.CODPLPAG = PCPLPAG.CODPLPAG
   AND PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND DECODE(PCNFSAID.CODGERENTE,NULL,PCSUPERV.CODGERENTE,PCNFSAID.CODGERENTE) = PCGERENTE.CODGERENTE 
   AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
   AND (PCNFSAID.DTCANCEL IS NULL)
   AND (PCPRODUT.CODFORNEC IN ( 16154,32194 )) 
   AND PCNFSAID.DTSAIDA BETWEEN  TO_DATE('01/02/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('28/02/2023', 'DD/MM/YYYY') 
           AND PCMOV.CODFILIAL IN('1','2','3','4','7','8','9','11','12','13','14','16')
           AND PCNFSAID.CODFILIAL IN('1','2','3','4','7','8','9','11','12','13','14','16')
           )
ORDER BY 2,1

