SELECT * FROM (SELECT 
LPAD (1, 2, 0) || '|' ||
'VENDAS' || '|' ||
LPAD (50, 3, 0) || '|' ||
:SEQUENCIA || '|' ||
TO_CHAR(SYSDATE-1,'YYYYMMDDhhmi')|| '|' ||
TO_CHAR(SYSDATE-1,'YYYYMMDD')|| '|' ||
TO_CHAR(SYSDATE-1,'YYYYMMDD') || '|' ||
'13987222000191' || '|' ||
'07216054000138',1
FROM DUAL
union all
SELECT 
LPAD (2, 2, 0) || '|' ||
LPAD (1, 2, 0) || '|' ||
LPAD(P.NUMNOTA,20,0) || '|' ||
LPAD (1, 2, 0) || '|' ||
case 
when P.CODOPER='S' then '01'
when P.CODOPER='ST' then '01'
when P.CODOPER='SR' then '01'
when P.CODOPER='ED' then '02'
 else '02' end || '|' ||
TO_CHAR(P.DTMOV,'YYYYMMDD')|| '|' ||
LPAD (0, 20, 0) || '|' ||
LPAD(REPLACE(REPLACE(REPLACE(CGCENT,'-',''),'.',''),'/',''),20,0)|| '|' ||
'RJ' || '|' ||
'21010410' || '|' ||
C.ESTCOB || '|' ||
LPAD (0, 8, 0) || '|' ||
'CIF' || '|' ||
LPAD (1, 2, 0) ,P.NUMNOTA
FROM PCMOV P
left join PCCLIENT c on  p.codcli = c.codcli
wHERE 
p.NUMNOTA in(
    SELECT 
       PCMOV.numnota
  FROM PCNFSAID,
       PCPRODUT,
       PCMOV,
       PCCLIENT,
       PCUSUARI,
       PCSUPERV,
       PCPLPAG,
       PCFORNEC,
       PCATIVI, 
       PCPRACA,
       PCDEPTO,
       PCSECAO,
       PCPEDC,
       PCGERENTE,
       PCCIDADE,
       PCMARCA,
       PCROTAEXP,
       PCMOVCOMPLE
 WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
   AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL 
   AND PCMOV.DTMOV BETWEEN  TO_DATE('01/04/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('30/04/2023', 'DD/MM/YYYY') 
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND PCNFSAID.CODPRACA = PCPRACA.CODPRACA(+)
   AND PCATIVI.CODATIV(+) = PCCLIENT.CODATV1
   AND PCMOV.CODCLI = PCCLIENT.CODCLI
   AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
   AND  PCNFSAID.CODUSUR   = PCUSUARI.CODUSUR 
   AND PCPRACA.ROTA = PCROTAEXP.CODROTA(+)
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
  AND PCMOV.CODOPER <> 'SR' 
  AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR', 'DF')
  AND PCMOV.CODOPER <> 'SO' 
   AND  NVL(PCNFSAID.CODSUPERVISOR,PCSUPERV.CODSUPERVISOR)   = PCSUPERV.CODSUPERVISOR
   AND PCNFSAID.CODPLPAG = PCPLPAG.CODPLPAG
   AND PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND DECODE(PCNFSAID.CODGERENTE,NULL,PCSUPERV.CODGERENTE,PCNFSAID.CODGERENTE) = PCGERENTE.CODGERENTE 
   AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
   AND (PCNFSAID.DTCANCEL IS NULL)
   AND (PCPRODUT.CODFORNEC IN ( 16154,32194 )) 
   AND (PCPRODUT.CODPRODPRINC IN ( 1430 )) 
   AND PCNFSAID.DTSAIDA BETWEEN  TO_DATE('01/04/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('30/04/2023', 'DD/MM/YYYY') 
           AND PCMOV.CODFILIAL IN('1')
           AND PCNFSAID.CODFILIAL IN('1')

) 
UNION ALL

SELECT 
LPAD (3, 2, 0) || '|' ||
LPAD(P.NUMNOTA,20,0) || '|' ||
LPAD (1, 2, 0) || '|' ||
case 
when P.CODOPER='S' then '01'
when P.CODOPER='ST' then '01'
when P.CODOPER='SR' then '01'
when P.CODOPER='ED' then '02'
 else '01' end || '|' ||
LPAD (P.CODPROD, 13, ' ') || '|' ||
LPAD (p.qt, 2, 0) || '|' ||
case when P.PUNIT < 1 then TO_CHAR(P.PUNIT,'0.99')
when P.PUNIT < 1 then TO_CHAR(P.PUNIT,'0.99')
 else TO_CHAR(P.PUNIT,'999.99') end || '|' ||
LPAD ('N', 1, 0) || '|' ||
case when P.QT*P.PUNIT < 1 then TO_CHAR(P.QT*P.PUNIT,'0.99') when P.QT*P.PUNIT > 1 and P.QT*P.PUNIT < 99999 then TO_CHAR(P.QT*P.PUNIT,'99999.99') else TO_CHAR(P.QT*P.PUNIT,'999999.99') end || '|' ||
--case when P.QT*P.PUNIT < 1 then TO_CHAR(P.QT*P.PUNIT,'0.99') else TO_CHAR(P.QT*P.PUNIT,'99999.99') end || '|' ||
case when P.QT*P.PUNIT < 1 then TO_CHAR(P.QT*P.PUNIT,'0.99') when P.QT*P.PUNIT > 1 and P.QT*P.PUNIT < 99999 then TO_CHAR(P.QT*P.PUNIT,'99999.99') else TO_CHAR(P.QT*P.PUNIT,'999999.99') end || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0) || '|' ||
LPAD (0, 2, 0),P.NUMNOTA
FROM PCMOV P
left join PCCLIENT c on  p.codcli = c.codcli
wHERE 
p.NUMNOTA in(
    SELECT 
       PCMOV.numnota
  FROM PCNFSAID,
       PCPRODUT,
       PCMOV,
       PCCLIENT,
       PCUSUARI,
       PCSUPERV,
       PCPLPAG,
       PCFORNEC,
       PCATIVI, 
       PCPRACA,
       PCDEPTO,
       PCSECAO,
       PCPEDC,
       PCGERENTE,
       PCCIDADE,
       PCMARCA,
       PCROTAEXP,
       PCMOVCOMPLE
 WHERE PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
   AND PCMOV.CODFILIAL = PCNFSAID.CODFILIAL 
   AND PCMOV.DTMOV BETWEEN  TO_DATE('01/04/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('30/04/2023', 'DD/MM/YYYY') 
   AND PCMOV.CODPROD = PCPRODUT.CODPROD
   AND PCNFSAID.CODPRACA = PCPRACA.CODPRACA(+)
   AND PCATIVI.CODATIV(+) = PCCLIENT.CODATV1
   AND PCMOV.CODCLI = PCCLIENT.CODCLI
   AND PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
   AND  PCNFSAID.CODUSUR   = PCUSUARI.CODUSUR 
   AND PCPRACA.ROTA = PCROTAEXP.CODROTA(+)
   AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM(+)
   AND PCPRODUT.CODMARCA = PCMARCA.CODMARCA(+)
   AND PCCLIENT.CODCIDADE = PCCIDADE.CODCIDADE(+)
  AND PCMOV.CODOPER <> 'SR' 
  AND NVL(PCNFSAID.TIPOVENDA,'X') NOT IN ('SR', 'DF')
  AND PCMOV.CODOPER <> 'SO' 
   AND  NVL(PCNFSAID.CODSUPERVISOR,PCSUPERV.CODSUPERVISOR)   = PCSUPERV.CODSUPERVISOR
   AND PCNFSAID.CODPLPAG = PCPLPAG.CODPLPAG
   AND PCNFSAID.NUMPED = PCPEDC.NUMPED(+)
   AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
   AND PCPRODUT.CODSEC = PCSECAO.CODSEC(+)
   AND DECODE(PCNFSAID.CODGERENTE,NULL,PCSUPERV.CODGERENTE,PCNFSAID.CODGERENTE) = PCGERENTE.CODGERENTE 
   AND PCNFSAID.CODFISCAL NOT IN (522, 622, 722, 532, 632, 732)
   AND PCNFSAID.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)
   AND (PCNFSAID.DTCANCEL IS NULL)
   AND (PCPRODUT.CODFORNEC IN ( 16154,32194 )) 
  -- AND (PCPRODUT.CODPRODPRINC IN ( 1430 )) 
   AND PCNFSAID.DTSAIDA BETWEEN  TO_DATE('01/04/2023', 'DD/MM/YYYY') AND 
                                 TO_DATE('30/04/2023', 'DD/MM/YYYY') 
           AND PCMOV.CODFILIAL IN('1')
           AND PCNFSAID.CODFILIAL IN('1')

) )
ORDER BY 2,1
